import React from 'react';
import { Button, Card } from 'components';


class Home extends React.Component {
  render() {
    return(
      <>
       <Button>Delete the list</Button>
       <Button styleType="action">Add a new card</Button>
       <Card title="title one" imgSrc="/assets/images/thumbs-up-png.png" imgAlt="thumbs-up"/>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed rutrum quam, gravida bibendum dui. Morbi quis mauris ut libero lacinia porttitor nec ut justo. Nunc nec risus nec eros ornare molestie sit amet ut nulla. Nullam bibendum porttitor lorem. In magna sem, euismod ultricies odio et, tempor cursus massa. Proin pharetra enim non nibh tempus, nec sagittis nulla sodales. Suspendisse commodo ullamcorper nisl, in pulvinar sapien aliquet viverra.</p>

        <p>Fusce sem mi, ultricies ac eros suscipit, porttitor convallis purus. Donec in consequat sem, quis tristique nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam lacinia id mi hendrerit ullamcorper. Morbi a viverra enim. Duis tortor nulla, sodales et faucibus id, maximus in lacus. Quisque id odio vel leo ornare aliquet.</p>

        <p>Nullam ligula velit, ultrices nec dapibus id, posuere sit amet nunc. Nulla sed ultrices diam, sit amet consequat nulla. Nulla facilisi. Nulla turpis elit, imperdiet dapibus sem a, imperdiet mattis nisi. Integer quis dictum tortor. Nullam viverra, augue eget condimentum mattis, tortor leo sollicitudin elit, ut convallis justo nisi ullamcorper sapien. Pellentesque nec accumsan sapien. Ut id eros sagittis, tempor purus eget, maximus dui. Vivamus massa ante, egestas a tortor ut, fermentum molestie risus. Cras sodales interdum lacus, non sodales sem posuere ac. In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer finibus ut urna eget auctor.</p>

        <p>Ut scelerisque sem at libero condimentum, vitae sagittis neque faucibus. Nulla elit nulla, commodo vitae efficitur eu, condimentum eu libero. Morbi ullamcorper arcu id tempor eleifend. Phasellus scelerisque dui in gravida semper. Ut a facilisis mauris. Vestibulum ut porta orci. Nulla facilisi. Maecenas quis augue leo. Nulla vitae magna condimentum, semper purus quis, facilisis massa. Vivamus maximus erat ut quam posuere ornare. Maecenas aliquet placerat ipsum, in rutrum diam fermentum eu. Quisque elementum laoreet interdum. Vestibulum laoreet velit dapibus justo ornare, at tincidunt dolor rhoncus. Sed scelerisque, nibh nec facilisis suscipit, neque neque varius mi, sed efficitur risus tellus id mi. Aliquam scelerisque, massa et vulputate condimentum, lacus ex lacinia mi, quis auctor orci leo ut justo. In hac habitasse platea dictumst.</p>

        <p>Morbi augue ante, elementum a ullamcorper at, varius in libero. In dignissim tortor vel pharetra aliquam. Cras porta sem est, ut imperdiet nulla varius in. In condimentum nunc non blandit molestie. Integer auctor ante mattis justo aliquam, non semper dui sollicitudin. Ut tincidunt eros sit amet volutpat aliquam. Quisque volutpat diam eget purus aliquet consequat. Nullam efficitur justo quis odio hendrerit, interdum imperdiet augue pretium. Nunc semper gravida massa eu aliquam. Aliquam rutrum, magna in dapibus tempus, metus sapien interdum purus, vulputate congue ipsum leo eget erat. Quisque quis vestibulum enim. Nulla ornare tincidunt ultrices. Aenean pellentesque sapien metus, et vehicula urna vestibulum pellentesque. Aliquam erat volutpat. Morbi quis lacinia sem, eu ornare nibh. Sed sollicitudin pellentesque massa sit amet pharetra.</p>

        <p>Quisque nulla enim, pulvinar id ullamcorper quis, suscipit sed diam. Praesent sodales magna semper orci pulvinar fermentum. Integer facilisis quam sed magna vehicula efficitur. Integer tempus sodales cursus. Praesent velit massa, bibendum quis sem ac, blandit volutpat leo. Aliquam quis urna vitae neque ullamcorper tincidunt eget at massa. Morbi aliquet aliquam felis, eu finibus ex auctor eget. Quisque id metus dictum, bibendum libero et, pretium magna. In a lacus a erat tincidunt congue. Ut dapibus pulvinar felis, eget hendrerit arcu congue vel. Pellentesque id odio ut nibh tincidunt semper. Sed in nibh euismod, consectetur turpis a, hendrerit odio. Nulla interdum sit amet diam nec mattis. Sed sit amet tincidunt odio. Aliquam tristique nunc et velit lobortis tincidunt.</p>

        <p>Curabitur id cursus risus. Curabitur venenatis tellus ut est malesuada aliquam. Ut fringilla et dui sed tristique. Nullam varius mollis odio eget auctor. Nam ultricies non est at pretium. Nam metus lorem, laoreet condimentum ultricies eget, ornare eget tellus. Suspendisse a felis ut ipsum vestibulum suscipit. Vestibulum mi lorem, viverra vel mattis nec, posuere vitae leo. Sed tincidunt nibh non mollis ultrices. Aliquam felis nulla, facilisis eu augue sed, dictum elementum eros. Aenean ultricies, eros at semper maximus, eros felis commodo mauris, sed luctus ante augue ut sem. Nunc nec sapien dignissim, lobortis justo vel, tincidunt urna. Ut ullamcorper pretium facilisis. Phasellus mollis cursus euismod.</p>

        <p>Morbi a justo quam. Donec consectetur magna urna, quis sodales ligula tincidunt et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet malesuada ligula. Cras quis risus sit amet leo semper hendrerit a ac urna. Pellentesque in quam porttitor, placerat erat non, bibendum justo. Nam eget nisl vulputate arcu vulputate porttitor. Vivamus dignissim felis magna, non aliquet dolor sodales quis.</p>

        <p>Nam venenatis mi dictum mauris tempor elementum. Nam leo velit, luctus sed pharetra eget, ullamcorper vel turpis. Proin ultrices euismod urna commodo bibendum. Sed congue purus at turpis mattis, vel efficitur ante molestie. Aliquam erat volutpat. Nam pulvinar pellentesque blandit. Sed at neque id erat finibus tincidunt tristique ut lectus. Phasellus sit amet mi vitae urna tincidunt vestibulum. Ut dictum nunc quis erat pretium, in venenatis nunc sollicitudin. Fusce eu porttitor diam. Praesent varius arcu id odio vulputate, eget egestas elit ultricies. Mauris tempor erat vel massa fermentum, nec maximus est condimentum. Pellentesque porta eros vitae dui tincidunt, id ultrices magna tempor.</p>

        <p>Sed at mattis nulla. Cras diam ligula, luctus vel porta a, gravida quis tortor. Ut est est, mattis id finibus sit amet, venenatis sed felis. Aenean condimentum, turpis vitae condimentum pretium, magna eros egestas risus, in rutrum orci eros eget sem. Integer vitae massa tempor, viverra sem et, finibus dui. Aliquam iaculis laoreet libero, sit amet aliquam ex ultrices non. Praesent eget est ac lectus facilisis lacinia sed sit amet sapien. Sed aliquet volutpat congue. Pellentesque euismod dui mi, nec laoreet lectus viverra a. Cras sollicitudin, enim a viverra eleifend, arcu felis varius purus, a euismod mi ipsum nec ex. Nulla at est sem.</p>
    </>
    )
  }
}

export default Home;